-------------------------------------------------------------------
-- CATEGORY 1: CUSTOMER DEMOGRAPHICS & SEGMENTATION
-------------------------------------------------------------------

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender, 
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2. What is the revenue contribution of each age group?
SELECT 
    age_group, 
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Q3. How do our customers segment into New, Returning, and Loyal based on their total number of previous purchases, and what is the count of each segment?
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment, 
    COUNT(*) AS "Number of Customers" 
FROM customer_type 
GROUP BY customer_segment;

-------------------------------------------------------------------
-- CATEGORY 2: LOYALTY & SUBSCRIPTION VALUE
-------------------------------------------------------------------

-- Q4. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q5. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-------------------------------------------------------------------
-- CATEGORY 3: PRODUCT PERFORMANCE & PREFERENCES
-------------------------------------------------------------------

-- Q6. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank, 
    category, 
    item_purchased, 
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q7. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased, 
    ROUND(AVG(review_rating::numeric), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q8. What are the most popular size and color combinations overall?
SELECT 
    category, 
    size, 
    color, 
    COUNT(customer_id) AS items_sold
FROM customer
GROUP BY category, size, color
ORDER BY items_sold DESC
LIMIT 10;

-------------------------------------------------------------------
-- CATEGORY 4: OPERATIONS, SHIPPING & PAYMENTS
-------------------------------------------------------------------

-- Q9. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    shipping_type, 
    ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q10. Which payment methods are most frequently used, and how much total revenue does each process?
SELECT 
    payment_method, 
    COUNT(customer_id) AS usage_count, 
    SUM(purchase_amount) AS total_processed
FROM customer
GROUP BY payment_method
ORDER BY usage_count DESC;

-------------------------------------------------------------------
-- CATEGORY 5: DISCOUNT IMPACT & PSYCHOLOGY
-------------------------------------------------------------------

-- Q11. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id, 
    purchase_amount 
FROM customer 
WHERE discount_applied = 'Yes' 
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q12. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q13. Do discounts impact customer satisfaction? Compare average ratings for discounted vs. non-discounted items.
SELECT 
    discount_applied, 
    ROUND(AVG(review_rating::numeric), 2) AS avg_rating, 
    COUNT(customer_id) AS total_reviews
FROM customer
GROUP BY discount_applied;

-------------------------------------------------------------------
-- CATEGORY 6: GEOGRAPHY & SEASONALITY
-------------------------------------------------------------------

-- Q14. Which 5 states or locations generate the highest total revenue?
SELECT 
    location, 
    COUNT(customer_id) AS total_orders, 
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 5;

-- Q15. How does purchasing behavior and average order value change across different seasons?
SELECT 
    season, 
    COUNT(customer_id) AS total_orders, 
    SUM(purchase_amount) AS total_revenue, 
    ROUND(AVG(purchase_amount), 2) AS avg_order_value
FROM customer
GROUP BY season
ORDER BY total_revenue DESC;